import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { Box, Heading, Spinner } from "@chakra-ui/react";
import SearchBar from "@/components/searchBar";
import { KeyboardEvent, useState, useRef } from "react";
import { useContext } from "react";
import Link from "next/link";
import { GlobalContext } from "@/context/context";

export default function Home() {
  const [keyPressed, setKeyPressed] = useState(false);
  const { loading } = useContext(GlobalContext);

  return (
    <>
      <Head>
        <title>DomainScan</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box
        display={"flex"}
        flexDirection={"column"}
        padding={"15rem"}
        backgroundImage={"/bg.jpg"}
        backgroundSize={"cover"}
        backgroundPosition={"center"}
        height={"100vh"}
      >
        <Box
          display={"flex"}
          justifyContent={"center"}
          alignItems={"center"}
          paddingBottom={"5px"}
        >
          <Image src="/logo2.png" width={70} height={70} alt="logo" />
          <Heading
            display={"flex"}
            justifyContent={"center"}
            fontFamily={"sans-serif"}
          >
            DomainScan
          </Heading>
        </Box>

        <Box display={"flex"} justifyContent={"center"} alignItems={"center"}>
          <SearchBar />
        </Box>
        {loading ? (
          <Box
            marginTop={8}
            display={"flex"}
            justifyContent={"center"}
            alignItems={"center"}
          >
            <Spinner />
          </Box>
        ) : (
          ""
        )}
      </Box>
    </>
  );
}
