import Nav from "@/components/Nav";
import Head from "next/head";
import { useRouter } from "next/router";
import { Box } from "@chakra-ui/react";
export default function Address() {
  const router = useRouter();
  const { query } = router;

  return (
    <>
      <Head>
        <title>{query.address}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box>
        <Nav />
      </Box>
    </>
  );
}
